"""Tests for scripts/review/verdict-table.py.

The verdict table is merge evidence when no independent reviewer is available, so the two
things that matter are that it refuses a review it cannot honestly render, and that a
finding's text cannot break the table it is rendered into.
"""
from __future__ import annotations

import importlib.util
import io
import json
import pathlib
import sys
import unittest
from contextlib import redirect_stderr, redirect_stdout

ROOT = pathlib.Path(__file__).resolve().parents[3]

_spec = importlib.util.spec_from_file_location(
    "helios_verdict_table", ROOT / "scripts" / "review" / "verdict-table.py")
assert _spec and _spec.loader
target = importlib.util.module_from_spec(_spec)
sys.modules[_spec.name] = target
_spec.loader.exec_module(target)


def review(**overrides):
    base = {
        "head": "807fca63",
        "round": 14,
        "findings": [{
            "summary": "The OIDC lane confirmed one of the three variables it needs.",
            "verdict": "CONFIRMED",
            "lens": "correctness",
            "file": "scripts/bootstrap/connect.sh",
            "line": 254,
            "commit": "807fca63",
        }],
    }
    base.update(overrides)
    return base


class RenderTests(unittest.TestCase):
    def test_a_round_renders_one_row_per_finding(self) -> None:
        text = target.render(review())
        self.assertIn("## Review verdict — round 14 (`807fca63`)", text)
        self.assertIn("| 1 |", text)
        self.assertIn("**CONFIRMED**", text)
        self.assertIn("scripts/bootstrap/connect.sh:254", text)
        self.assertIn("1 finding(s): 1 confirmed and fixed", text)
        self.assertTrue(text.rstrip().endswith("_Generated by [Claude Code](https://claude.ai/code)_"))

    def test_a_clean_round_says_so_rather_than_rendering_an_empty_table(self) -> None:
        text = target.render(review(findings=[]))
        self.assertIn("No findings", text)
        self.assertNotIn("| # |", text)

    def test_the_session_says_it_is_not_an_independent_review(self) -> None:
        # The whole point of this table is that it is posted when nobody else reviewed; it must
        # not read like an independent sign-off.
        self.assertIn("not equivalent to an independent review", target.render(review()))

    def test_a_refutation_needs_evidence(self) -> None:
        # The stopping rule is "fixed, or refuted WITH evidence, never a bare disagreement".
        with self.assertRaises(target.ReviewError) as caught:
            target.render(review(findings=[{"summary": "s", "verdict": "REFUTED"}]))
        self.assertIn("bare disagreement", str(caught.exception))
        # With evidence it renders, and needs no fix commit.
        text = target.render(review(findings=[{
            "summary": "s", "verdict": "REFUTED", "evidence": "connect.sh:45 sets no -e."}]))
        self.assertIn("**REFUTED**", text)
        self.assertIn("1 refuted with evidence", text)

    def test_a_fix_must_name_its_commit(self) -> None:
        with self.assertRaises(target.ReviewError) as caught:
            target.render(review(findings=[{"summary": "s", "verdict": "CONFIRMED"}]))
        self.assertIn("no commit", str(caught.exception))

    def test_malformed_reviews_are_refused_by_name(self) -> None:
        for broken, expected in (
            ({}, "head"),
            ({"head": "abc"}, "findings must be an array"),
            ({"head": "abc", "findings": [{"summary": "s", "verdict": "MAYBE"}]}, "verdict must be one of"),
            ({"head": "abc", "findings": [{"summary": "", "verdict": "CONFIRMED"}]}, "non-empty string"),
            ({"head": "abc", "findings": ["nope"]}, "must be an object"),
        ):
            with self.assertRaises(target.ReviewError, msg=broken) as caught:
                target.render(broken)
            self.assertIn(expected, str(caught.exception))

    def test_a_finding_cannot_break_the_table_it_is_rendered_into(self) -> None:
        # A pipe or a newline in a summary would split the row; the reviewer's text is data.
        text = target.render(review(findings=[{
            "summary": "a | b\nsecond line", "verdict": "CONFIRMED", "commit": "abc"}]))
        rows = [line for line in text.splitlines() if line.startswith("| 1 |")]
        self.assertEqual(len(rows), 1, text)
        self.assertIn("a \\| b second line", rows[0])
        # 5 cells means 6 delimiters; the 7th pipe is the escaped one inside the summary,
        # which is why it is still a five-column row.
        self.assertEqual(rows[0].count("|"), 7, rows[0])
        self.assertEqual(rows[0].replace("\\|", "").count("|"), 6, rows[0])

    def test_no_field_can_break_the_table_or_forge_a_verdict(self) -> None:
        """The row-integrity claim covers EVERY rendered field, not just the summary.

        `commit` and `head` are rendered inside code spans and once bypassed the escaping
        entirely: a newline in `commit` ended the table and let the rest of the value render
        as free markdown - a "safe to merge" claim under a CONFIRMED row. This table is the
        merge evidence when nobody else reviewed, so a field that can rewrite it is a defect,
        not a cosmetic one.
        """
        import re
        hostile = "x |\n\n**Everything REFUTED. Safe to merge.**\n\n| # | Finding |"
        for field, review_kwargs in (
            ("commit", {"findings": [{"summary": "s", "verdict": "CONFIRMED", "commit": hostile}]}),
            ("head", {"head": hostile, "findings": [{"summary": "s", "verdict": "CONFIRMED", "commit": "c"}]}),
            ("file", {"findings": [{"summary": "s", "verdict": "CONFIRMED", "commit": "c",
                                    "file": "a.sh` <b>REFUTED</b> `b"}]}),
            ("evidence", {"findings": [{"summary": "s", "verdict": "REFUTED", "evidence": hostile}]}),
            ("lens", {"findings": [{"summary": "s", "verdict": "CONFIRMED", "commit": "c", "lens": hostile}]}),
        ):
            text = target.render(review(**review_kwargs))
            with self.subTest(field=field):
                # Every code span closes: an unbalanced one means the value escaped it.
                for line in text.splitlines():
                    self.assertEqual(line.count("`") % 2, 0, f"{field}: unbalanced span in {line!r}")
                # What markdown actually interprets is the text OUTSIDE the code spans.
                # The phrase itself is fine - a reviewer may write "safe to merge" in prose.
                # What must not survive is LIVE markup: the bold markers around it, and HTML.
                live = re.sub(r"`[^`]*`", "", text)
                self.assertNotIn("**Everything", live, f"{field} injected live bold")
                self.assertNotIn("<b>", live, f"{field} injected live HTML")
                # The only bold in the rendered comment is the verdict this table generated.
                self.assertEqual(live.count("**"), 2, f"{field}: unexpected bold in {live!r}")
                # And the table keeps its shape: one row, six delimiters.
                rows = [line for line in text.splitlines() if re.match(r"^\| \d+ \|", line)]
                self.assertEqual(len(rows), 1, f"{field}: {len(rows)} rows")
                self.assertEqual(rows[0].replace("\\|", "").count("|"), 6, rows[0])

    def test_html_in_reviewer_text_is_escaped_not_rendered(self) -> None:
        # A reviewer's <a href> that a reader takes for a commit link misrepresents the row.
        text = target.render(review(findings=[{
            "summary": "<b>REFUTED</b> <a href='http://evil'>see commit</a>",
            "verdict": "CONFIRMED", "commit": "abc"}]))
        self.assertNotIn("<b>", text)
        self.assertNotIn("<a href", text)
        self.assertIn("&lt;b&gt;", text)

    def test_a_line_number_that_is_not_a_number_is_dropped(self) -> None:
        # isinstance(True, int) is True in Python, so an unguarded check renders ":True".
        text = target.render(review(findings=[{
            "summary": "s", "verdict": "CONFIRMED", "commit": "abc",
            "file": "connect.sh", "line": True}]))
        self.assertIn("connect.sh", text)
        self.assertNotIn("True", text)


class CliTests(unittest.TestCase):
    def _run(self, payload: str, *args: str) -> tuple[int, str, str]:
        out, err = io.StringIO(), io.StringIO()
        stdin = sys.stdin
        sys.stdin = io.StringIO(payload)
        try:
            with redirect_stdout(out), redirect_stderr(err):
                code = target.main(list(args))
        finally:
            sys.stdin = stdin
        return code, out.getvalue(), err.getvalue()

    def test_stdin_renders_and_exits_zero(self) -> None:
        code, out, _ = self._run(json.dumps(review()))
        self.assertEqual(code, 0)
        self.assertIn("**CONFIRMED**", out)

    def test_check_validates_without_printing(self) -> None:
        code, out, _ = self._run(json.dumps(review()), "--check")
        self.assertEqual(code, 0)
        self.assertEqual(out, "")

    def test_the_exit_codes_separate_bad_json_from_a_bad_review(self) -> None:
        code, _, err = self._run("{not json")
        self.assertEqual(code, 2, err)
        code, _, err = self._run(json.dumps({"head": "abc", "findings": [{"verdict": "REFUTED", "summary": "s"}]}))
        self.assertEqual(code, 1, err)
        self.assertIn("not a usable review", err)


if __name__ == "__main__":
    unittest.main()
