#!/usr/bin/env pwsh
#Requires -Version 7.0
<#
.SYNOPSIS
    Reconciles the repo's label manifest (config/github/labels.json) with the live
    GitHub labels: creates missing labels, patches drifted color/description, never
    deletes. Dry-run by default; -Apply executes.

.DESCRIPTION
    The labels sibling of scripts/github/apply-rulesets.ps1 (branch rulesets) and
    scripts/github/apply-repo-settings.ps1 (scalar repository settings). It keeps
    their shape so the governance workflow can drive all four scripts the same way:

      GET the live labels -> for every manifest entry match by NAME (case-insensitive,
      because GitHub itself treats label names as unique case-insensitively) ->
      missing? print the exact `gh api --method POST` line : color or description
      drifted? print the exact `gh api --method PATCH` line : in sync -> report a
      no-op.

    The command is printed BEFORE it is executed on purpose: if the process dies
    mid-pass (network, environment policy) the operator still holds the replay
    line. A failed item never aborts the pass: the remaining labels are still
    reconciled and the script exits 1 with a consolidated replay list of every
    item that did not land.

    Never deletes: a live label that is not in the manifest is listed as
    "unmanaged" and left alone, because labels carry issue history and the
    manifest is a floor, not a fence. A PATCH never renames either: the live
    name (any case) is kept as the endpoint, so "Feature" stays "Feature".

    Credential: labels are an ISSUES resource, not an administration one. The
    Actions GITHUB_TOKEN with `issues: write` (what .github/workflows/governance-apply.yml
    grants) or a fine-grained PAT with "Issues: write" is enough; repository admin
    is NOT required, so unlike the rulesets/settings siblings this script does not
    gate on .permissions.admin. The precondition is only that the wire can read the
    repository (`gh api repos/{repo}` exit 0, the rest-connect.ps1 doctrine that the
    REST wire is the ground truth and `gh auth status` is never consulted). Write
    ability is proven by the first mutation: a 403 there is reported as a failed
    item with its replay line instead of being guessed up front.

    Manifest shape (config/github/labels.json): an object with a `$comment` and a
    `labels` array of { name, color, description }; a bare array of entries is
    accepted too. color is six hex digits (a leading '#' is tolerated), description
    at most 100 characters (GitHub's limit). Those three are the ONLY keys an entry
    may carry: any other key (a typo such as `descr`, or `aliases`, which this
    script does not support) marks the entry invalid (exit 1, key named) instead of
    being silently dropped and read as "in sync".

    Wire: every `gh api` call carries `X-GitHub-Api-Version: 2022-11-28` (gh 2.63.2
    sends none by itself); a 429, or a 403 naming the rate/secondary limit, is
    retried once after Retry-After (60 s when absent); mutations are paced >= 1 s
    apart. Descriptions written through an attribution-injecting proxy (the Claude
    container) come back with a trailing `_Generated by [Claude Code]_` footer,
    which the next governance run reconciles as an ordinary description PATCH.

.PARAMETER Apply
    Execute the `gh api` calls. Without it the script only prints them (dry run).

.PARAMETER Repository
    Target repository as owner/name. Defaults to Yolkster64/helios-platform.

.PARAMETER ManifestPath
    Path to the label manifest. Defaults to config/github/labels.json relative to
    this checkout.

.PARAMETER Json
    Emit exactly one JSON object on stdout (mode, precondition, per-label items with
    their state and replay command, counts, exit code) and nothing else; every human
    line is suppressed. The exit-code contract is unchanged.

.EXAMPLE
    pwsh scripts/github/apply-labels.ps1
    # dry run: shows create/update/in-sync per label and every command it would run

.EXAMPLE
    pwsh scripts/github/apply-labels.ps1 -Apply
    # applies; needs a wire credential with issues:write on the repository

.EXAMPLE
    pwsh scripts/github/apply-labels.ps1 -Json
    # one JSON object for machine consumers (setup-all.ps1 / first-run style); the
    # governance workflow reads the human output instead

.NOTES
    Exit codes: 0 = success (or clean dry run); 1 = manifest missing/invalid, an
    entry invalid, or an item failed to apply (replay list printed); 2 = gh CLI or
    a usable wire credential unavailable in -Apply mode.
    Secrets: no token value is ever read, stored, or printed; gh reads its own
    credential (GH_TOKEN by NAME, or the keyring) and this script only sees exit
    codes and label JSON.
#>
[CmdletBinding()]
param(
    [switch]$Apply,

    [string]$Repository = 'Yolkster64/helios-platform',

    [string]$ManifestPath,

    [switch]$Json
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if (-not $ManifestPath) {
    $repoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
    $ManifestPath = Join-Path $repoRoot 'config' 'github' 'labels.json'
}

$mode = if ($Apply) { 'apply' } else { 'dry-run' }

# One result model feeds both the console lines and -Json, so the two views can
# never disagree about what was planned or what landed.
$result = [ordered]@{
    script       = 'apply-labels'
    mode         = $mode
    repository   = $Repository
    manifest     = $ManifestPath
    precondition = [ordered]@{ ghFound = $false; wireReadable = $false; existenceKnown = $false }
    items        = [System.Collections.Generic.List[object]]::new()
    unmanaged    = [System.Collections.Generic.List[string]]::new()
    notes        = [System.Collections.Generic.List[string]]::new()
    counts       = [ordered]@{ create = 0; update = 0; inSync = 0; failed = 0; invalid = 0 }
    exitCode     = 0
}

# Under -Json stdout must carry exactly one object, and pwsh routes Write-Host AND
# Write-Warning to stdout, so every human line goes through this gate instead.
function Write-Line {
    param([string]$Text)
    if (-not $Json) { Write-Host $Text }
}

function Add-Note {
    param([string]$Text)
    $result.notes.Add($Text)
    Write-Line "note: $Text"
}

# Single exit path: records the code in the result, emits the one JSON object when
# asked, and exits. Called from the top level only, so `exit` ends the script.
function Exit-With {
    param([int]$Code)
    $result.exitCode = $Code
    if ($Json) { $result | ConvertTo-Json -Depth 6 }
    exit $Code
}

# StrictMode-safe property access on parsed JSON (rest-connect.ps1 pattern): a
# missing property must read as the default, not throw.
function Get-OptionalProperty {
    param($Object, [string]$Name, $Default = $null)
    if ($null -eq $Object) { return $Default }
    $prop = $Object.PSObject.Properties[$Name]
    if ($null -ne $prop -and $null -ne $prop.Value) { return $prop.Value }
    return $Default
}

# Renders one argv element the way an operator would retype it in a POSIX shell,
# so the printed replay line is copy-paste safe even when a description carries an
# apostrophe ("Something isn't working").
function ConvertTo-ShellArg {
    param([string]$Value)
    if ($Value -match '^[A-Za-z0-9_./:=@%-]+$') { return $Value }
    return "'" + ($Value -replace "'", "'\''") + "'"
}

# --- gh api wire layer (identical across scripts/github/*.ps1; keep in copy-sync) ------
# Every call carries the pinned REST version: gh 2.63.2 sends no X-GitHub-Api-Version
# by itself, and an unpinned call opts into whatever the default becomes. The same
# prefix heads every printed replay line, so an operator retypes exactly this call.
$script:GhApiArgs = @('api', '-H', 'X-GitHub-Api-Version: 2022-11-28')
$script:GhApiReplay = "gh api -H 'X-GitHub-Api-Version: 2022-11-28'"
$script:LastMutationUtc = [DateTime]::UtcNow.AddSeconds(-5)

# One gh api call. -i puts the status line and headers in front of the body, so the
# HTTP status and Retry-After are known without echoing anything from the wire
# (stderr is discarded). Stdout is captured FIRST and $LASTEXITCODE read at once.
# On a non-zero exit the reply's own {status,message} decide whether GitHub was rate
# limiting (429, or a 403 whose message names the rate/secondary limit): the call
# then sleeps Retry-After seconds (60 when the header is absent) and retries ONCE.
# Every other failure returns as-is: a 4xx would fail identically, and a blind retry
# of a POST could double-create. -Mutating paces writes >= 1 s apart (GitHub's
# secondary limit is ~80 content-creating requests per minute).
# Returns {ExitCode, HttpStatus, Text, Json}; HttpStatus is 0 when no reply arrived.
function Invoke-GhApi {
    param(
        [Parameter(Mandatory)][string[]]$GhArgs,
        [switch]$Mutating
    )
    if (-not $script:gh) { return [pscustomobject]@{ ExitCode = 127; HttpStatus = 0; Text = ''; Json = $null } }
    $retried = $false
    while ($true) {
        if ($Mutating) {
            $elapsed = ([DateTime]::UtcNow - $script:LastMutationUtc).TotalMilliseconds
            if ($elapsed -lt 1000) { Start-Sleep -Milliseconds ([int](1000 - $elapsed)) }
        }
        $argv = $script:GhApiArgs + @('-i') + $GhArgs
        $raw = @(& $script:gh.Source @argv 2>$null)
        $code = $LASTEXITCODE
        if ($Mutating) { $script:LastMutationUtc = [DateTime]::UtcNow }
        $lines = @($raw | ForEach-Object { ([string]$_).TrimEnd("`r") })
        $blank = [Array]::IndexOf($lines, '')
        $headers = @(if ($blank -gt 0) { $lines[0..($blank - 1)] })
        $body = @(if ($blank -ge 0) { $lines | Select-Object -Skip ($blank + 1) })
        $status = 0
        if ($headers.Count -gt 0 -and $headers[0] -match '^HTTP/\S+\s+(\d{3})') { $status = [int]$Matches[1] }
        $text = ($body -join "`n").Trim()
        $parsed = $null
        if ($text) { try { $parsed = $text | ConvertFrom-Json -NoEnumerate } catch { $parsed = $null } }
        if ($code -ne 0 -and -not $retried) {
            $message = [string](Get-OptionalProperty $parsed 'message' '')
            if ($status -eq 0 -and ([string](Get-OptionalProperty $parsed 'status' '')) -match '^\d{3}$') { $status = [int]$Matches[0] }
            if ($status -eq 429 -or ($status -eq 403 -and $message -match 'rate limit|secondary')) {
                $retryAfter = 60
                foreach ($h in $headers) { if ($h -match '^Retry-After:\s*(\d+)') { $retryAfter = [int]$Matches[1] } }
                Start-Sleep -Seconds $retryAfter
                $retried = $true
                continue
            }
        }
        return [pscustomobject]@{ ExitCode = $code; HttpStatus = $status; Text = $text; Json = $parsed }
    }
}

Write-Line "apply-labels: mode=$mode repository=$Repository manifest=$ManifestPath"

# --- Wire-truth precondition (same probe family as apply-rulesets.ps1 / apply-repo-
# --- settings.ps1, minus the admin field: labels need issues:write, not admin, and
# --- GITHUB_TOKEN reports .permissions.push=false even when it can write issues, so
# --- gating on any permission flag would refuse a credential that works). The
# --- wrapper captures the body; only the exit code is consulted.
$gh = Get-Command gh -CommandType Application -ErrorAction SilentlyContinue | Select-Object -First 1
$wireOk = $false
if ($gh) {
    $result.precondition.ghFound = $true
    if ((Invoke-GhApi -GhArgs @("repos/$Repository")).ExitCode -eq 0) { $wireOk = $true }
    $result.precondition.wireReadable = $wireOk
}
if ($Apply -and -not $gh) {
    Write-Line 'apply-labels: FAILED PRECONDITION - the GitHub CLI (gh) is not on PATH.'
    Write-Line 'Install it (https://cli.github.com/); re-run without -Apply for a dry run.'
    Add-Note 'gh CLI not on PATH'
    Exit-With 2
}
if ($Apply -and -not $wireOk) {
    Write-Line "apply-labels: FAILED PRECONDITION - the wire probe could not read repos/$Repository."
    Write-Line 'No usable GitHub credential answered on the REST wire. Authenticate first:'
    Write-Line '"gh auth login", or scripts/bootstrap/connect-github.sh --from-env (persists a'
    Write-Line 'REST-valid GH_TOKEN non-interactively), or set the GH_TOKEN environment variable'
    Write-Line '(the NAME of the variable to set - never put the value in a file or argument).'
    Write-Line 'Labels need issues:write on the repository (Actions GITHUB_TOKEN with'
    Write-Line '`issues: write`, or a fine-grained PAT with "Issues: write"); admin is not required.'
    Add-Note "wire probe could not read repos/$Repository"
    Exit-With 2
}

# --- Manifest -----------------------------------------------------------------------
if (-not (Test-Path -LiteralPath $ManifestPath -PathType Leaf)) {
    Write-Line "apply-labels: manifest not found: $ManifestPath"
    Add-Note "manifest not found: $ManifestPath"
    Exit-With 1
}
$manifestDoc = $null
try {
    # -NoEnumerate keeps a bare top-level array AS an array: without it ConvertFrom-Json
    # streams the elements, so a one-entry manifest arrives as a lone object, fails the
    # array test below, and the documented bare-array form would exit 1.
    $manifestDoc = Get-Content -LiteralPath $ManifestPath -Raw | ConvertFrom-Json -NoEnumerate
}
catch {
    Write-Line "apply-labels: invalid JSON in $ManifestPath - $($_.Exception.Message)"
    Add-Note "invalid JSON in manifest: $($_.Exception.Message)"
    Exit-With 1
}
# Accept both the object form ({ "$comment", "labels": [...] }, the repo's config
# convention) and a bare array, so hand-written manifests need no wrapper.
$entries = @()
if ($manifestDoc -is [System.Array]) {
    $entries = @($manifestDoc)
}
else {
    $entries = @(Get-OptionalProperty $manifestDoc 'labels' @())
}
if ($entries.Count -eq 0) {
    Write-Line "apply-labels: manifest has no label entries ($ManifestPath)"
    Add-Note 'manifest has no label entries'
    Exit-With 1
}

# --- Live labels (explicit per_page/page loop rather than --paginate so the output
# --- is one JSON array per call, parsed page by page; the page cap only guards
# --- against a runaway loop, no real repository approaches 2000 labels). ------------
$existing = @()
$existenceKnown = $false
if ($gh -and $wireOk) {
    $page = 1
    $listOk = $true
    while ($true) {
        $pageRead = Invoke-GhApi -GhArgs @("repos/$Repository/labels?per_page=100&page=$page")
        if ($pageRead.ExitCode -ne 0) { $listOk = $false; break }
        if ($pageRead.Text -and $null -eq $pageRead.Json) { $listOk = $false; break }
        $batch = @($pageRead.Json)
        $existing += $batch
        if ($batch.Count -lt 100 -or $page -ge 20) { break }
        $page++
    }
    $existenceKnown = $listOk
}
$result.precondition.existenceKnown = $existenceKnown
if (-not $existenceKnown) {
    if ($Apply) {
        Write-Line "apply-labels: could not list existing labels for $Repository (gh api failed)."
        Write-Line 'Without the live list an apply could duplicate or clobber labels, so nothing was changed.'
        Add-Note 'could not list existing labels'
        Exit-With 2
    }
    Add-Note 'existing labels unknown (gh or credential unavailable); dry run shows POST for every entry, a real run re-checks and switches to PATCH where the label exists'
}
Write-Line "apply-labels: live labels=$($existing.Count) manifest entries=$($entries.Count)"
Write-Line ''

# --- Reconcile ----------------------------------------------------------------------
$failures = [System.Collections.Generic.List[string]]::new()
$managedNames = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)

foreach ($entry in $entries) {
    $name = ([string](Get-OptionalProperty $entry 'name' '')).Trim()
    $color = ([string](Get-OptionalProperty $entry 'color' '')).Trim().TrimStart('#').ToLowerInvariant()
    $description = [string](Get-OptionalProperty $entry 'description' '')
    $item = [ordered]@{ name = $name; state = ''; command = ''; detail = '' }

    # Validate before touching the wire: GitHub would reject these anyway, but a
    # local verdict names the manifest line instead of a 422 body. Unknown keys are
    # rejected too: a typo (`descr`) would otherwise vanish and the row read "in sync".
    $allowedKeys = @('name', 'color', 'description')
    $unknownKeys = @($entry.PSObject.Properties.Name | Where-Object { $allowedKeys -notcontains $_ })
    $problem = $null
    if (-not $name) { $problem = 'entry has no name' }
    elseif ($unknownKeys.Count -gt 0) { $problem = "unknown key(s) $($unknownKeys -join ', ') (allowed: $($allowedKeys -join ', '))" }
    elseif ($color -notmatch '^[0-9a-f]{6}$') { $problem = "color '$color' is not six hex digits" }
    elseif ($description.Length -gt 100) { $problem = "description is $($description.Length) characters (GitHub caps it at 100)" }
    if ($problem) {
        $item.state = 'invalid'
        $item.detail = $problem
        $result.items.Add([pscustomobject]$item)
        $result.counts.invalid++
        $failures.Add("[$name] INVALID manifest entry: $problem")
        Write-Line "  [$name] INVALID manifest entry - $problem"
        continue
    }
    $null = $managedNames.Add($name)

    $live = $existing | Where-Object { ([string](Get-OptionalProperty $_ 'name' '')) -ieq $name } | Select-Object -First 1
    $ghArgs = @()
    if ($null -eq $live) {
        $item.state = 'create'
        $item.detail = if ($existenceKnown) { 'no live label with this name' } else { 'live labels unknown; assuming create' }
        $ghArgs = @('--method', 'POST', "repos/$Repository/labels",
            '-f', "name=$name", '-f', "color=$color", '-f', "description=$description")
    }
    else {
        $liveName = [string](Get-OptionalProperty $live 'name' $name)
        $liveColor = ([string](Get-OptionalProperty $live 'color' '')).Trim().TrimStart('#').ToLowerInvariant()
        $liveDescription = [string](Get-OptionalProperty $live 'description' '')
        $drift = [System.Collections.Generic.List[string]]::new()
        if ($liveColor -ne $color) { $drift.Add("color $liveColor -> $color") }
        if ($liveDescription -cne $description) { $drift.Add("description '$liveDescription' -> '$description'") }
        if ($drift.Count -eq 0) {
            $item.state = 'in-sync'
            $result.items.Add([pscustomobject]$item)
            $result.counts.inSync++
            Write-Line "  [$name] in sync ($color)"
            continue
        }
        $item.state = 'update'
        $item.detail = ($drift -join '; ')
        # The live name is the endpoint (URL-encoded: "good first issue" has spaces)
        # and is deliberately not passed as new_name, so a PATCH never renames.
        $encoded = [uri]::EscapeDataString($liveName)
        $ghArgs = @('--method', 'PATCH', "repos/$Repository/labels/$encoded",
            '-f', "color=$color", '-f', "description=$description")
    }

    $rendered = $script:GhApiReplay + ' ' + (($ghArgs | ForEach-Object { ConvertTo-ShellArg $_ }) -join ' ')
    $item.command = $rendered
    if (-not $Apply) {
        Write-Line "  [$name] $($item.state) - $($item.detail)"
        Write-Line "  [$name] would run: $rendered"
        $result.items.Add([pscustomobject]$item)
        if ($item.state -eq 'create') { $result.counts.create++ } else { $result.counts.update++ }
        continue
    }

    Write-Line "  [$name] $($item.state) - $($item.detail)"
    Write-Line "  [$name] applying: $rendered"
    $run = Invoke-GhApi -GhArgs $ghArgs -Mutating
    if ($run.ExitCode -eq 0) {
        $item.state = if ($item.state -eq 'create') { 'created' } else { 'updated' }
        if ($item.state -eq 'created') { $result.counts.create++ } else { $result.counts.update++ }
        Write-Line "  [$name] $($item.state)."
    }
    else {
        $item.state = 'failed'
        $item.detail = "gh exited $($run.ExitCode), HTTP $($run.HttpStatus) (a 403 here means the credential lacks issues:write); $($item.detail)"
        $result.counts.failed++
        $failures.Add("[$name] $rendered")
        Write-Line "  [$name] FAILED (gh exited $($run.ExitCode), HTTP $($run.HttpStatus)) - replay: $rendered"
    }
    $result.items.Add([pscustomobject]$item)
}

# --- Unmanaged live labels: reported, never deleted. ---------------------------------
if ($existenceKnown) {
    foreach ($live in $existing) {
        $liveName = [string](Get-OptionalProperty $live 'name' '')
        if ($liveName -and -not $managedNames.Contains($liveName)) { $result.unmanaged.Add($liveName) }
    }
    if ($result.unmanaged.Count -gt 0) {
        Write-Line ''
        Write-Line "  unmanaged live labels (left alone, this script never deletes): $($result.unmanaged -join ', ')"
    }
}

# --- Rollup --------------------------------------------------------------------------
Write-Line ''
$c = $result.counts
if ($failures.Count -gt 0) {
    Write-Line "apply-labels: $($failures.Count) item(s) FAILED - replay list:"
    foreach ($f in $failures) { Write-Line "  $f" }
    Write-Line 'Each command line is directly re-runnable by an identity with issues:write on the repository.'
    Exit-With 1
}
if ($Apply) {
    Write-Line "apply-labels: complete - created=$($c.create) updated=$($c.update) in-sync=$($c.inSync)."
    Write-Line 'Idempotence check: re-run this script and expect every row to read "in sync".'
}
else {
    Write-Line "apply-labels: dry run complete - create=$($c.create) update=$($c.update) in-sync=$($c.inSync). Nothing was changed. Re-run with -Apply to execute the commands above."
}
Exit-With 0
