#!/usr/bin/env pwsh
#Requires -Version 7.0
<#
.SYNOPSIS
    Reconciles the repo's milestone manifest (config/github/milestones.json) with the
    live GitHub milestones: creates missing ones, patches drifted description/due
    date, never closes or deletes. Dry-run by default; -Apply executes.

.DESCRIPTION
    The milestones sibling of scripts/github/apply-labels.ps1, with the same shape so
    .github/workflows/governance-apply.yml drives both identically:

      GET the live milestones (state=all) -> for every manifest entry match by TITLE
      (case-insensitive) -> missing? print the exact `gh api --method POST` line :
      open and drifted? print the exact `gh api --method PATCH` line : in sync ->
      report a no-op.

    The command is printed BEFORE it is executed so an interrupted pass still leaves
    the replay line on the console; a failed item never aborts the pass, and the
    script exits 1 with a consolidated replay list of everything that did not land.

    Never closes, reopens, or deletes: a CLOSED milestone whose title matches is
    reported as "closed (left untouched)" and skipped, because reopening a milestone
    is a planning decision, not a drift fix. Live milestones absent from the manifest
    are listed as "unmanaged" and left alone.

    Due dates: the manifest carries a calendar date (YYYY-MM-DD). GitHub normalizes a
    milestone's due_on to Pacific midnight and reports it as 07:00Z/08:00Z, so the
    script sends noon UTC (safe in both the UTC and the Pacific reading of the
    date) and compares only the UTC calendar date of the live value; that is what
    makes a second run read "in sync" instead of re-patching forever. A blank or
    absent due_on in the manifest means "not managed": it is neither sent nor
    compared, so this script can never clear a due date.

    Credential: milestones live under the Issues permission. The Actions
    GITHUB_TOKEN with `issues: write` or a fine-grained PAT with "Issues: write" is
    enough; repository admin is NOT required, so the precondition is only that the
    wire can read the repository (`gh api repos/{repo}` exit 0; `gh auth status` is
    never consulted, per the rest-connect.ps1 doctrine). Write ability is proven by
    the first mutation, and a 403 there is a failed item with its replay line.

    Manifest shape (config/github/milestones.json): an object with a `$comment` and a
    `milestones` array of { title, description, due_on }; a bare array is accepted.
    Those three are the ONLY keys an entry may carry: any other key (a typo such as
    `dueOn` or `descr`, or `state`, which this script does not manage) marks the
    entry invalid (exit 1, key named) instead of being silently dropped and read
    as "in sync".

    Wire: every `gh api` call carries `X-GitHub-Api-Version: 2022-11-28` (gh 2.63.2
    sends none by itself); a 429, or a 403 naming the rate/secondary limit, is
    retried once after Retry-After (60 s when absent); mutations are paced >= 1 s
    apart. Descriptions written through an attribution-injecting proxy (the Claude
    container) come back with a trailing `_Generated by [Claude Code]_` footer,
    which the next governance run reconciles as an ordinary description PATCH.

.PARAMETER Apply
    Execute the `gh api` calls. Without it the script only prints them (dry run).

.PARAMETER Repository
    Target repository as owner/name. Defaults to Yolkster64/helios-platform.

.PARAMETER ManifestPath
    Path to the milestone manifest. Defaults to config/github/milestones.json
    relative to this checkout.

.PARAMETER Json
    Emit exactly one JSON object on stdout (mode, precondition, per-milestone items
    with their state and replay command, counts, exit code) and nothing else.

.EXAMPLE
    pwsh scripts/github/apply-milestones.ps1
    # dry run: shows create/update/in-sync per milestone and every command it would run

.EXAMPLE
    pwsh scripts/github/apply-milestones.ps1 -Apply
    # applies; needs a wire credential with issues:write on the repository

.NOTES
    Exit codes: 0 = success (or clean dry run); 1 = manifest missing/invalid, an
    entry invalid, or an item failed to apply (replay list printed); 2 = gh CLI or
    a usable wire credential unavailable in -Apply mode.
    Secrets: no token value is ever read, stored, or printed.
#>
[CmdletBinding()]
param(
    [switch]$Apply,

    [string]$Repository = 'Yolkster64/helios-platform',

    [string]$ManifestPath,

    [switch]$Json
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if (-not $ManifestPath) {
    $repoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
    $ManifestPath = Join-Path $repoRoot 'config' 'github' 'milestones.json'
}

$mode = if ($Apply) { 'apply' } else { 'dry-run' }

# One result model feeds both the console lines and -Json (see apply-labels.ps1).
$result = [ordered]@{
    script       = 'apply-milestones'
    mode         = $mode
    repository   = $Repository
    manifest     = $ManifestPath
    precondition = [ordered]@{ ghFound = $false; wireReadable = $false; existenceKnown = $false }
    items        = [System.Collections.Generic.List[object]]::new()
    unmanaged    = [System.Collections.Generic.List[string]]::new()
    notes        = [System.Collections.Generic.List[string]]::new()
    counts       = [ordered]@{ create = 0; update = 0; inSync = 0; closed = 0; failed = 0; invalid = 0 }
    exitCode     = 0
}

# Under -Json stdout must carry exactly one object; pwsh sends Write-Host and
# Write-Warning to stdout, so every human line passes through this gate.
function Write-Line {
    param([string]$Text)
    if (-not $Json) { Write-Host $Text }
}

function Add-Note {
    param([string]$Text)
    $result.notes.Add($Text)
    Write-Line "note: $Text"
}

# Single exit path (top level only, so `exit` ends the script).
function Exit-With {
    param([int]$Code)
    $result.exitCode = $Code
    if ($Json) { $result | ConvertTo-Json -Depth 6 }
    exit $Code
}

# StrictMode-safe property access on parsed JSON (rest-connect.ps1 pattern).
function Get-OptionalProperty {
    param($Object, [string]$Name, $Default = $null)
    if ($null -eq $Object) { return $Default }
    $prop = $Object.PSObject.Properties[$Name]
    if ($null -ne $prop -and $null -ne $prop.Value) { return $prop.Value }
    return $Default
}

# POSIX-shell quoting for the printed replay line (descriptions carry spaces,
# parentheses and apostrophes).
function ConvertTo-ShellArg {
    param([string]$Value)
    if ($Value -match '^[A-Za-z0-9_./:=@%-]+$') { return $Value }
    return "'" + ($Value -replace "'", "'\''") + "'"
}

# --- gh api wire layer (identical across scripts/github/*.ps1; keep in copy-sync) ------
# Every call carries the pinned REST version: gh 2.63.2 sends no X-GitHub-Api-Version
# by itself, and an unpinned call opts into whatever the default becomes. The same
# prefix heads every printed replay line, so an operator retypes exactly this call.
$script:GhApiArgs = @('api', '-H', 'X-GitHub-Api-Version: 2022-11-28')
$script:GhApiReplay = "gh api -H 'X-GitHub-Api-Version: 2022-11-28'"
$script:LastMutationUtc = [DateTime]::UtcNow.AddSeconds(-5)

# One gh api call. -i puts the status line and headers in front of the body, so the
# HTTP status and Retry-After are known without echoing anything from the wire
# (stderr is discarded). Stdout is captured FIRST and $LASTEXITCODE read at once.
# On a non-zero exit the reply's own {status,message} decide whether GitHub was rate
# limiting (429, or a 403 whose message names the rate/secondary limit): the call
# then sleeps Retry-After seconds (60 when the header is absent) and retries ONCE.
# Every other failure returns as-is: a 4xx would fail identically, and a blind retry
# of a POST could double-create. -Mutating paces writes >= 1 s apart (GitHub's
# secondary limit is ~80 content-creating requests per minute).
# Returns {ExitCode, HttpStatus, Text, Json}; HttpStatus is 0 when no reply arrived.
function Invoke-GhApi {
    param(
        [Parameter(Mandatory)][string[]]$GhArgs,
        [switch]$Mutating
    )
    if (-not $script:gh) { return [pscustomobject]@{ ExitCode = 127; HttpStatus = 0; Text = ''; Json = $null } }
    $retried = $false
    while ($true) {
        if ($Mutating) {
            $elapsed = ([DateTime]::UtcNow - $script:LastMutationUtc).TotalMilliseconds
            if ($elapsed -lt 1000) { Start-Sleep -Milliseconds ([int](1000 - $elapsed)) }
        }
        $argv = $script:GhApiArgs + @('-i') + $GhArgs
        $raw = @(& $script:gh.Source @argv 2>$null)
        $code = $LASTEXITCODE
        if ($Mutating) { $script:LastMutationUtc = [DateTime]::UtcNow }
        $lines = @($raw | ForEach-Object { ([string]$_).TrimEnd("`r") })
        $blank = [Array]::IndexOf($lines, '')
        $headers = @(if ($blank -gt 0) { $lines[0..($blank - 1)] })
        $body = @(if ($blank -ge 0) { $lines | Select-Object -Skip ($blank + 1) })
        $status = 0
        if ($headers.Count -gt 0 -and $headers[0] -match '^HTTP/\S+\s+(\d{3})') { $status = [int]$Matches[1] }
        $text = ($body -join "`n").Trim()
        $parsed = $null
        if ($text) { try { $parsed = $text | ConvertFrom-Json -NoEnumerate } catch { $parsed = $null } }
        if ($code -ne 0 -and -not $retried) {
            $message = [string](Get-OptionalProperty $parsed 'message' '')
            if ($status -eq 0 -and ([string](Get-OptionalProperty $parsed 'status' '')) -match '^\d{3}$') { $status = [int]$Matches[0] }
            if ($status -eq 429 -or ($status -eq 403 -and $message -match 'rate limit|secondary')) {
                $retryAfter = 60
                foreach ($h in $headers) { if ($h -match '^Retry-After:\s*(\d+)') { $retryAfter = [int]$Matches[1] } }
                Start-Sleep -Seconds $retryAfter
                $retried = $true
                continue
            }
        }
        return [pscustomobject]@{ ExitCode = $code; HttpStatus = $status; Text = $text; Json = $parsed }
    }
}

# GitHub reports due_on as a Pacific-midnight instant (07:00Z or 08:00Z); only the
# UTC calendar date is stable across that normalization, so that is what is compared.
function Get-UtcDate {
    param([string]$Iso)
    if ([string]::IsNullOrWhiteSpace($Iso)) { return '' }
    try {
        $dto = [System.DateTimeOffset]::Parse($Iso, [System.Globalization.CultureInfo]::InvariantCulture)
        return $dto.UtcDateTime.ToString('yyyy-MM-dd')
    }
    catch { return '' }
}

Write-Line "apply-milestones: mode=$mode repository=$Repository manifest=$ManifestPath"

# --- Wire-truth precondition: gh on PATH and a credential that reads the repo.
# --- No admin/push flag is consulted (milestones need issues:write, and GITHUB_TOKEN
# --- reports push=false even when it can write issues). The wrapper captures the body.
$gh = Get-Command gh -CommandType Application -ErrorAction SilentlyContinue | Select-Object -First 1
$wireOk = $false
if ($gh) {
    $result.precondition.ghFound = $true
    if ((Invoke-GhApi -GhArgs @("repos/$Repository")).ExitCode -eq 0) { $wireOk = $true }
    $result.precondition.wireReadable = $wireOk
}
if ($Apply -and -not $gh) {
    Write-Line 'apply-milestones: FAILED PRECONDITION - the GitHub CLI (gh) is not on PATH.'
    Write-Line 'Install it (https://cli.github.com/); re-run without -Apply for a dry run.'
    Add-Note 'gh CLI not on PATH'
    Exit-With 2
}
if ($Apply -and -not $wireOk) {
    Write-Line "apply-milestones: FAILED PRECONDITION - the wire probe could not read repos/$Repository."
    Write-Line 'No usable GitHub credential answered on the REST wire. Authenticate first:'
    Write-Line '"gh auth login", or scripts/bootstrap/connect-github.sh --from-env, or set the'
    Write-Line 'GH_TOKEN environment variable (by NAME - never put the value in a file or argument).'
    Write-Line 'Milestones need issues:write on the repository; admin is not required.'
    Add-Note "wire probe could not read repos/$Repository"
    Exit-With 2
}

# --- Manifest -----------------------------------------------------------------------
if (-not (Test-Path -LiteralPath $ManifestPath -PathType Leaf)) {
    Write-Line "apply-milestones: manifest not found: $ManifestPath"
    Add-Note "manifest not found: $ManifestPath"
    Exit-With 1
}
$manifestDoc = $null
try {
    # -NoEnumerate keeps a bare top-level array AS an array: without it ConvertFrom-Json
    # streams the elements, so a one-entry manifest arrives as a lone object, fails the
    # array test below, and the documented bare-array form would exit 1.
    $manifestDoc = Get-Content -LiteralPath $ManifestPath -Raw | ConvertFrom-Json -NoEnumerate
}
catch {
    Write-Line "apply-milestones: invalid JSON in $ManifestPath - $($_.Exception.Message)"
    Add-Note "invalid JSON in manifest: $($_.Exception.Message)"
    Exit-With 1
}
$entries = @()
if ($manifestDoc -is [System.Array]) { $entries = @($manifestDoc) }
else { $entries = @(Get-OptionalProperty $manifestDoc 'milestones' @()) }
if ($entries.Count -eq 0) {
    Write-Line "apply-milestones: manifest has no milestone entries ($ManifestPath)"
    Add-Note 'manifest has no milestone entries'
    Exit-With 1
}

# --- Live milestones, state=all so a closed match is recognized (and skipped) rather
# --- than re-created as a duplicate open one. Explicit page loop, capped only as a
# --- runaway guard. ----------------------------------------------------------------
$existing = @()
$existenceKnown = $false
if ($gh -and $wireOk) {
    $page = 1
    $listOk = $true
    while ($true) {
        $pageRead = Invoke-GhApi -GhArgs @("repos/$Repository/milestones?state=all&per_page=100&page=$page")
        if ($pageRead.ExitCode -ne 0) { $listOk = $false; break }
        if ($pageRead.Text -and $null -eq $pageRead.Json) { $listOk = $false; break }
        $batch = @($pageRead.Json)
        $existing += $batch
        if ($batch.Count -lt 100 -or $page -ge 20) { break }
        $page++
    }
    $existenceKnown = $listOk
}
$result.precondition.existenceKnown = $existenceKnown
if (-not $existenceKnown) {
    if ($Apply) {
        Write-Line "apply-milestones: could not list existing milestones for $Repository (gh api failed)."
        Write-Line 'Without the live list an apply could create duplicates, so nothing was changed.'
        Add-Note 'could not list existing milestones'
        Exit-With 2
    }
    Add-Note 'existing milestones unknown (gh or credential unavailable); dry run shows POST for every entry, a real run re-checks and switches to PATCH where the title exists'
}
Write-Line "apply-milestones: live milestones=$($existing.Count) manifest entries=$($entries.Count)"
Write-Line ''

# --- Reconcile ----------------------------------------------------------------------
$failures = [System.Collections.Generic.List[string]]::new()
$managedTitles = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)

foreach ($entry in $entries) {
    $title = ([string](Get-OptionalProperty $entry 'title' '')).Trim()
    $description = [string](Get-OptionalProperty $entry 'description' '')
    $dueDate = ([string](Get-OptionalProperty $entry 'due_on' '')).Trim()
    $item = [ordered]@{ title = $title; state = ''; command = ''; detail = '' }

    # Unknown keys are rejected: a typo (`dueOn`) would otherwise vanish and the row
    # read "in sync" while the intended due date never lands.
    $allowedKeys = @('title', 'description', 'due_on')
    $unknownKeys = @($entry.PSObject.Properties.Name | Where-Object { $allowedKeys -notcontains $_ })
    $problem = $null
    if (-not $title) { $problem = 'entry has no title' }
    elseif ($unknownKeys.Count -gt 0) { $problem = "unknown key(s) $($unknownKeys -join ', ') (allowed: $($allowedKeys -join ', '))" }
    elseif ($dueDate -and $dueDate -notmatch '^\d{4}-\d{2}-\d{2}$') { $problem = "due_on '$dueDate' is not a YYYY-MM-DD date" }
    elseif ($dueDate -and -not (Get-UtcDate "${dueDate}T12:00:00Z")) { $problem = "due_on '$dueDate' is not a real calendar date" }
    if ($problem) {
        $item.state = 'invalid'
        $item.detail = $problem
        $result.items.Add([pscustomobject]$item)
        $result.counts.invalid++
        $failures.Add("[$title] INVALID manifest entry: $problem")
        Write-Line "  [$title] INVALID manifest entry - $problem"
        continue
    }
    $null = $managedTitles.Add($title)
    # Noon UTC keeps the calendar date intact under GitHub's Pacific normalization.
    $dueWire = if ($dueDate) { "${dueDate}T12:00:00Z" } else { '' }

    $live = $existing | Where-Object { ([string](Get-OptionalProperty $_ 'title' '')) -ieq $title } | Select-Object -First 1
    $ghArgs = @()
    if ($null -eq $live) {
        $item.state = 'create'
        $item.detail = if ($existenceKnown) { 'no live milestone with this title' } else { 'live milestones unknown; assuming create' }
        $ghArgs = @('--method', 'POST', "repos/$Repository/milestones",
            '-f', "title=$title", '-f', "description=$description")
        if ($dueWire) { $ghArgs += @('-f', "due_on=$dueWire") }
    }
    else {
        $liveState = [string](Get-OptionalProperty $live 'state' 'open')
        $liveNumber = [string](Get-OptionalProperty $live 'number' '')
        if ($liveState -ne 'open') {
            $item.state = 'closed'
            $item.detail = "milestone #$liveNumber is $liveState; left untouched (this script never reopens, closes or deletes)"
            $result.items.Add([pscustomobject]$item)
            $result.counts.closed++
            Write-Line "  [$title] $($item.detail)"
            continue
        }
        $liveDescription = [string](Get-OptionalProperty $live 'description' '')
        $liveDue = Get-UtcDate ([string](Get-OptionalProperty $live 'due_on' ''))
        $drift = [System.Collections.Generic.List[string]]::new()
        if ($liveDescription -cne $description) { $drift.Add("description '$liveDescription' -> '$description'") }
        if ($dueDate -and $liveDue -ne $dueDate) { $drift.Add("due_on $(if ($liveDue) { $liveDue } else { '(none)' }) -> $dueDate") }
        if ($drift.Count -eq 0) {
            $item.state = 'in-sync'
            $result.items.Add([pscustomobject]$item)
            $result.counts.inSync++
            Write-Line "  [$title] in sync (#$liveNumber, due $(if ($liveDue) { $liveDue } else { 'unset' }))"
            continue
        }
        $item.state = 'update'
        $item.detail = ($drift -join '; ')
        $ghArgs = @('--method', 'PATCH', "repos/$Repository/milestones/$liveNumber",
            '-f', "description=$description")
        if ($dueWire) { $ghArgs += @('-f', "due_on=$dueWire") }
    }

    $rendered = $script:GhApiReplay + ' ' + (($ghArgs | ForEach-Object { ConvertTo-ShellArg $_ }) -join ' ')
    $item.command = $rendered
    if (-not $Apply) {
        Write-Line "  [$title] $($item.state) - $($item.detail)"
        Write-Line "  [$title] would run: $rendered"
        $result.items.Add([pscustomobject]$item)
        if ($item.state -eq 'create') { $result.counts.create++ } else { $result.counts.update++ }
        continue
    }

    Write-Line "  [$title] $($item.state) - $($item.detail)"
    Write-Line "  [$title] applying: $rendered"
    $run = Invoke-GhApi -GhArgs $ghArgs -Mutating
    if ($run.ExitCode -eq 0) {
        $item.state = if ($item.state -eq 'create') { 'created' } else { 'updated' }
        if ($item.state -eq 'created') { $result.counts.create++ } else { $result.counts.update++ }
        Write-Line "  [$title] $($item.state)."
    }
    else {
        $item.state = 'failed'
        $item.detail = "gh exited $($run.ExitCode), HTTP $($run.HttpStatus) (a 403 here means the credential lacks issues:write); $($item.detail)"
        $result.counts.failed++
        $failures.Add("[$title] $rendered")
        Write-Line "  [$title] FAILED (gh exited $($run.ExitCode), HTTP $($run.HttpStatus)) - replay: $rendered"
    }
    $result.items.Add([pscustomobject]$item)
}

# --- Unmanaged live milestones: reported, never closed or deleted. -------------------
if ($existenceKnown) {
    foreach ($live in $existing) {
        $liveTitle = [string](Get-OptionalProperty $live 'title' '')
        if ($liveTitle -and -not $managedTitles.Contains($liveTitle)) { $result.unmanaged.Add($liveTitle) }
    }
    if ($result.unmanaged.Count -gt 0) {
        Write-Line ''
        Write-Line "  unmanaged live milestones (left alone): $($result.unmanaged -join ', ')"
    }
}

# --- Rollup --------------------------------------------------------------------------
Write-Line ''
$c = $result.counts
if ($failures.Count -gt 0) {
    Write-Line "apply-milestones: $($failures.Count) item(s) FAILED - replay list:"
    foreach ($f in $failures) { Write-Line "  $f" }
    Write-Line 'Each command line is directly re-runnable by an identity with issues:write on the repository.'
    Exit-With 1
}
if ($Apply) {
    Write-Line "apply-milestones: complete - created=$($c.create) updated=$($c.update) in-sync=$($c.inSync) closed-skipped=$($c.closed)."
    Write-Line 'Idempotence check: re-run this script and expect every open row to read "in sync".'
}
else {
    Write-Line "apply-milestones: dry run complete - create=$($c.create) update=$($c.update) in-sync=$($c.inSync) closed-skipped=$($c.closed). Nothing was changed. Re-run with -Apply to execute the commands above."
}
Exit-With 0
