#!/usr/bin/env bash
# End-to-end Azure bring-up for the cloud-only AIHub:
#   device-code login -> resource group -> infra/main.bicep deployment -> env wiring.
#
# Everything the deployment returns is an endpoint or a name — never a secret — so the
# wiring lands in .helios/azure.env (gitignored) for `source`-ing into any shell.
#
# Usage:
#   scripts/bootstrap/azure-up.sh                             # defaults: rg-helios-ai, eastus2
#   scripts/bootstrap/azure-up.sh -g my-rg -l swedencentral
#   scripts/bootstrap/azure-up.sh --subscription <id> --skip-login
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
resource_group="rg-helios-ai"
location="eastus2"
subscription=""
skip_login=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    -g|--resource-group) resource_group="${2:?--resource-group needs a value}"; shift 2 ;;
    -l|--location) location="${2:?--location needs a value}"; shift 2 ;;
    --subscription) subscription="${2:?--subscription needs a value}"; shift 2 ;;
    --skip-login) skip_login=1; shift ;;
    *) echo "unknown argument: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$skip_login" ]]; then
  "$repo_root/scripts/bootstrap/connect-azure.sh" ${subscription:+--subscription "$subscription"}
elif [[ -n "$subscription" ]]; then
  az account set --subscription "$subscription"
fi

echo "Azure: ensuring resource group $resource_group in $location..."
az group create --name "$resource_group" --location "$location" --output none

# The signed-in user's objectId lets Bicep grant Azure AI User + Key Vault Secrets User,
# which is what makes keyless (Entra ID) azure-openai calls work right after deploy.
principal_id="$(az ad signed-in-user show --query id --output tsv 2>/dev/null || true)"
[[ -z "$principal_id" ]] && echo "warning: could not resolve signed-in user objectId; deploying without RBAC grants." >&2

echo "Azure: deploying infra/main.bicep (this creates the Foundry account + project + Key Vault)..."
deployment_name="helios-ai-up-$(date +%Y%m%d%H%M%S)"
outputs_json="$(az deployment group create \
  --name "$deployment_name" \
  --resource-group "$resource_group" \
  --template-file "$repo_root/infra/main.bicep" \
  ${principal_id:+--parameters principalId="$principal_id"} \
  --query properties.outputs --output json)"

get_out() { printf '%s' "$outputs_json" | python3 -c "import sys,json;print(json.load(sys.stdin).get('$1',{}).get('value',''))"; }
openai_endpoint="$(get_out openAiEndpoint)"
project_endpoint="$(get_out projectEndpoint)"
keyvault_uri="$(get_out keyVaultUri)"

env_file="$repo_root/.helios/azure.env"
mkdir -p "$repo_root/.helios"
cat > "$env_file" <<EOF
# Generated by scripts/bootstrap/azure-up.sh — endpoints only, never secrets.
export AZURE_OPENAI_ENDPOINT="$openai_endpoint"
export AZURE_FOUNDRY_PROJECT_ENDPOINT="$project_endpoint"
export AZURE_KEY_VAULT_URI="$keyvault_uri"
export AIHUB_CONFIG="$repo_root/config/aihub.cloud.json"
EOF

echo
echo "Deployment complete. Wire this shell (and any future one) with:"
echo "  source $env_file"
echo
echo "azure-openai then authenticates with your Entra ID login (no key needed)."
echo "Optional: source scripts/bootstrap/load-env-from-keyvault.sh to pull the"
echo "openai/anthropic/github-models API keys out of Key Vault."

if command -v dotnet >/dev/null 2>&1; then
  echo
  echo "Smoke: provider readiness under the cloud profile..."
  # shellcheck disable=SC1090
  source "$env_file"
  dotnet run --project "$repo_root/src/ai/HELIOS.AIHub.Cli" --framework net10.0 -- status || true
fi
