<#
.SYNOPSIS
End-to-end Azure bring-up for the cloud-only AIHub — Azure PowerShell twin of
azure-up.sh: device-code login -> resource group -> infra/main.bicep -> env wiring.

.DESCRIPTION
Everything the deployment returns is an endpoint or a name — never a secret — so the
wiring lands in .helios/azure.env.ps1 (gitignored) for dot-sourcing into any session.
Requires the Bicep CLI on PATH (New-AzResourceGroupDeployment compiles .bicep with it).

.EXAMPLE
pwsh scripts/bootstrap/azure-up.ps1
pwsh scripts/bootstrap/azure-up.ps1 -ResourceGroup my-rg -Location swedencentral
pwsh scripts/bootstrap/azure-up.ps1 -Subscription <id> -SkipLogin
#>
[CmdletBinding()]
param(
    [string]$ResourceGroup = 'rg-helios-ai',
    [string]$Location = 'eastus2',
    [string]$Subscription,
    [switch]$SkipLogin
)

$ErrorActionPreference = 'Stop'
$repoRoot = Resolve-Path (Join-Path $PSScriptRoot '../..')

if (-not $SkipLogin) {
    & (Join-Path $PSScriptRoot 'connect-azure.ps1') @(if ($Subscription) { '-Subscription', $Subscription })
}
elseif ($Subscription) {
    Set-AzContext -Subscription $Subscription | Out-Null
}

Write-Host "Azure: ensuring resource group $ResourceGroup in $Location..."
New-AzResourceGroup -Name $ResourceGroup -Location $Location -Force | Out-Null

# The signed-in user's objectId lets Bicep grant Azure AI User + Key Vault Secrets User,
# which is what makes keyless (Entra ID) azure-openai calls work right after deploy.
$principalId = (Get-AzADUser -SignedIn -ErrorAction SilentlyContinue).Id
if (-not $principalId) {
    Write-Warning 'could not resolve signed-in user objectId; deploying without RBAC grants.'
}

Write-Host 'Azure: deploying infra/main.bicep (this creates the Foundry account + project + Key Vault)...'
$parameters = @{}
if ($principalId) { $parameters.principalId = $principalId }
$deployment = New-AzResourceGroupDeployment `
    -Name "helios-ai-up-$(Get-Date -Format yyyyMMddHHmmss)" `
    -ResourceGroupName $ResourceGroup `
    -TemplateFile (Join-Path $repoRoot 'infra/main.bicep') `
    -TemplateParameterObject $parameters

$envFile = Join-Path $repoRoot '.helios/azure.env.ps1'
New-Item -ItemType Directory -Path (Join-Path $repoRoot '.helios') -Force | Out-Null
@"
# Generated by scripts/bootstrap/azure-up.ps1 — endpoints only, never secrets.
`$env:AZURE_OPENAI_ENDPOINT = '$($deployment.Outputs.openAiEndpoint.Value)'
`$env:AZURE_FOUNDRY_PROJECT_ENDPOINT = '$($deployment.Outputs.projectEndpoint.Value)'
`$env:AZURE_KEY_VAULT_URI = '$($deployment.Outputs.keyVaultUri.Value)'
`$env:AIHUB_CONFIG = '$(Join-Path $repoRoot 'config/aihub.cloud.json')'
"@ | Set-Content -Path $envFile

Write-Host ''
Write-Host 'Deployment complete. Wire this session (and any future one) with:'
Write-Host "  . $envFile"
Write-Host ''
Write-Host 'azure-openai then authenticates with your Entra ID login (no key needed).'
